name: Update M3U

on:
  schedule:
    - cron: "*/5 * * * *"

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run converter
        run: python update.py

      - name: Commit updated M3U
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add channels.m3u
          git commit -m "Auto update M3U" || echo "No changes"
          git push
